arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/fluxk.kt, arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/monok.kt, arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt, arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt, arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt, arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/singlek.kt, arrow-fx-test/src/main/kotlin/arrow/test/laws/TraverseLaws.kt, arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt, arrow-fx/src/main/kotlin/arrow/fx/typeclasses/ParApplicative.kt
Changes from https://github.com/arrow-kt/arrow-core/pull/23 broke every arrow build with an applicative instance, here is the fix.
This non-deterministically failed MVar tests locally. Is this linked to #46 ?
=> Change applicative instances to implement apEval and remove lazyAp

arrow-fx/src/main/kotlin/arrow/fx/IO.kt
Fix the code which is stumbled on an old type inference problem of the Kotlin compiler
Background.
The old type inference has some problems with common super type calculation on Unit-returning lambdas. Namely, in one of the following cases, the old type inference runs "coercion to Unit":
1) If in the place where common super type calculation is required (e.g. "if", "when", "select" function), the first candidate was a lambda which returns Unit (explicitly or implicitly);
2) If in any of the branches there was an explicit specifying of the returned functional type, namely, Unit in the return position.
This is the wrong behavior: type inference in such cases should still run common super type calculation. The new type inference behave correctly in such cases.
Problem with the changing code. …
=> Fix the code which is stumbled on an old type inference problem of the Kotlin compiler

arrow-docs/docs/fx/polymorphism/README.md, arrow-docs/docs/integrations/reactor/README.md, arrow-docs/docs/integrations/rx2/README.md
Original PR can be seen [here](https://github.com/arrow-kt/arrow-core/issues/26).
What version are you currently using? 0.10
What would you like to see?
The documentation includes Try examples. Since Try is deprecated, these examples should be removed (or transitioned to Either examples) to prevent confusion.
=> Removed (almost) all Try examples in documentation/comment blocks

arrow-benchmarks-fx/build.gradle, arrow-fx-kotlinx-coroutines/build.gradle, arrow-fx/build.gradle, arrow-fx/src/test/kotlin/arrow/fx/RefTest.kt
=> Enable ktlint

arrow-docs/build.gradle, arrow-fx-reactor/build.gradle, arrow-fx-rx2/build.gradle, arrow-fx-test/build.gradle, arrow-fx/build.gradle, arrow-streams/build.gradle
It's not necessary and it impacts on the use of the libraries (necessary dependencies).
I don't use "revert" to keep some improvements/orders done.
=> Undo unnecessary change

build.gradle
Remove binary-compatibility-validator because is automatically checking the api
=> Remove binary-compatibility-validator

arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/ConcurrentLaws.kt
Might improve the tests in https://github.com/arrow-kt/arrow-incubator/pull/85
=> Align ConcurrentLaws' cancellable and cancellableF tests

arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/ConcurrentLaws.kt, arrow-fx/src/test/kotlin/arrow/fx/QueueTest.kt
Add forFew to Queue test to unveil some race problems then fixed with a tiny sleep
Fixes #120
=> Fix Queue flaky tests

arrow-fx-kotlinx-coroutines/src/test/kotlin/arrow/integrations/kotlinx/CoroutinesIntegrationTest.kt, arrow-fx-test/src/main/kotlin/arrow/fx/test/eq.kt, arrow-fx-test/src/main/kotlin/arrow/fx/test/eq/EqK.kt, arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/Law.kt
PR on `release/0.11.0` branch.
cc @nomisRev , we left `eq.kt` outside `arrow.fx.test` package.
=> Fix package for eq

arrow-fx-kotlinx-coroutines/build.gradle
Fix #139 issue about the wrong scope for arrow-fx-kotlinx-coroutines dependencies.
=> Fix #139: Wrong scope for dependencies

arrow-docs/docs/fx/README.md
- Remove Ank for 2 code snippets with compilation errors.
- Show the exceptions for method calls.
More than 2 thousand lines with multiple span sections:
=> Fix #146: Reduce load time for Fx main page

.github/workflows/build_arrow-fx.yml, .github/workflows/publish_arrow-fx.yml, arrow-benchmarks-fx/build.gradle
This PR adds benchmark comparison via [Hood](https://47degrees.github.io/hood/) so a comment with the result will be added in every pull request on this repository. 
**See the comment below** as an example. 
That comment will be **updated** with new commits:
In this case there isn't difference between values because this pull request is just adding the configuration and it's not changing Arrow Fx library.
It only shows `Concurrentqueue` because it's the only benchmark included:
```
jmh {
include = [
'arrow.benchmarks.Queue'
]
...
}
```
For instance, for this configuration:
```
jmh {
include = [
'arrow.benchmarks.Async',
'arrow.benchmarks.Queue'
]
...
}
```
it would appear data for:
* Async.catsIO
* Async.io
* Async.scalazZIO
* Queue.concurrentQueue
**Default threshold** is being used. …
=> Solve #76. Add benchmark comparison

arrow-fx-android/build.gradle, build.gradle
PR on `ab/lifecycle-integration` branch-
Fix one of the TODO items from #158:
* Figure out if it's possible to move the root build.gradle's added config for android to the specific module
I followed this guide: https://developer.android.com/studio/build#build-files
=> arrow-fx-android: move Gradle configuration to the module

.github/workflows/build_arrow-fx.yml, arrow-benchmarks-fx/arrow-kio-benchmarks/build.gradle, arrow-benchmarks-fx/arrow-scala-benchmarks/build.gradle, arrow-benchmarks-fx/build.gradle, arrow-docs/build.gradle, arrow-fx-coroutines/build.gradle, arrow-fx-kotlinx-coroutines/build.gradle, arrow-fx-reactor/build.gradle, arrow-fx-rx2/build.gradle, arrow-fx-test/build.gradle, arrow-fx/build.gradle, arrow-streams/build.gradle, build.gradle, gradle.properties
PR on `sv-arrow-fx-coroutines` branch (PR #169 ).
- Just one environment.
- Parallel Gradle execution.
- Remove buildtimetracker forever .
- Remove animalsniffer temporarily. It's going to be isolated in a single check.
- useJUnitPlatform is specified in SUBPROJECT_CONF
=> Tuning configuration

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Schedule.kt, arrow-fx/src/main/kotlin/arrow/fx/Schedule.kt, arrow-fx/src/main/kotlin/arrow/fx/extensions/schedule.kt, arrow-fx/src/test/kotlin/arrow/fx/ScheduleTest.kt
* Fix schedule recurs #173 returning the number of total iterations, instead of repetitions
* Fix never #174 that should never repeat and basically hang the program
* Fix repeat not waiting for delay after first emission #172 
* Also removed Alternative and MonoidK instances as it might not have sense to provide Schedule.never() as MonoidK.empty()
=> Fixes to Schedule

.github/workflows/build_arrow-fx.yml
I was talking about our current problems with a heavy test process and this is one of the recommendations to improve it. 
How it works:
- `Cache management` step will add the use of the cache if it exists.
- A new final step is added automatically to create the cache.
SNAPSHOT dependencies are being used during development for the rest of Arrow libraries so I remove them before caching all the dependencies.
We're still having random errors:
```
arrow.fx.QueueTest > UnboundedQueue - queue can be filled at once over capacity with takers FAILED
arrow.fx.internal.TimeoutException: Duration(amount=5, timeUnit=SECONDS)
```
```
arrow.fx.coroutines.BracketCaseTest > Uncancellable back pressures timeoutOrNull STANDARD_ERROR
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines …
```
=> Configuration: Add cache management

.github/workflows/build_arrow-fx.yml, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/SuspendConnection.kt, arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt, gradle.properties
SuspendConnection now uses `Platform.unsafeRunSync` internally to cancel a token when the connection is already cancelled.
Instead it should use `startCoroutine` that runs on an empty context, which allows for the cancel token to fork and exit the existing context.
=> Fix issue SuspendConnection

.github/workflows/build_arrow-fx.yml
It's already fixed in `arrow` repository.
=> Configuration: recover the previous build step

arrow-fx-coroutines/build.gradle, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/predef-test.kt
In order to help to the progressive use of Kotest.
**Note**: it corresponds to `4.1.0` instead of `4.0.6`. Let's see if it works...
=> Use of KOTEST_VERSION property

.github/workflows/build_arrow-fx.yml
It will be possible to browse test reports despite of the build check result.
Example of failing tests: https://github.com/arrow-kt/arrow-fx/runs/818689776
=> Configuration: download test reports

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/timer.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ArrowFxSpec.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/PredefTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/TimerTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/predef-test.kt
- Fixes `timeOutOrNull` or null to return on the previous context.
@rachelcarmena @aballano
I suspect this was the reason for the flaky `Uncancellable back pressures timeoutOrNull` test.
So let's keep an eye on this together ;)
=> Fix timeOutOrNull to return on the  context

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTupledN.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Race2.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Race3.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/RacePair.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/RaceTriple.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/timer.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ArrowFxSpec.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/FiberTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ParTupledNTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/RaceNTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/RacePairTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/RaceTripleTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/TimerTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/predef-test.kt
Follow up PR #203, which exposed returning to incorrect contexts in `timeOutOrNull`.
This PR adds these tests for all operators and optimizes them further from `suspendCoroutine` to `suspendCoroutineUninterceptedOrReturn`.
All other operators in this PR were working correctly but add tests to prevent regression.
For example, the interception in `Fiber#join` comes from `suspendCoroutine` in the `cancellable` builder.
=> Complete test suite to check interception

.github/workflows/build_arrow-fx.yml, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/BracketCaseTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/TimerTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/StreamTest.kt
While testing CI in this branch I noticed the precision of `sleep` degrade in the tests, and this caused flakiness.
This PR
- increases the `sleep` duration for `Uncancellable back pressures timeoutOrNull`
- refactors `if a pipe is interrupted, it will not restart evaluation` to use `Promise` as a latch instead of `sleep` which makes it pass consistently in a now `checkAll` property test.
=> Fix flaky pipe test

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Compiler.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Pull.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/BracketTest.kt
When _pure_ interruption occurs, then `bracket` should be closed with `ExitCase.Cancelled`.
However when an error is thrown from the `release` function, then this should become the final result from the `Stream` since we do not want the `Stream` to silently finish when an error occurred.
This more the fix made in #210 into a separate PR.
=> Fix release after pure interruption

arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/BracketCaseTest.kt
As per https://github.com/arrow-kt/arrow-fx/pull/167#issuecomment-665791522
Change timed test to use measureTimedValue instead of manually calculating time to see if it prevents flakiness
=> Tweak Bracket test

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/concurrent/PubSub.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/concurrent/Queue.kt
Couple of small improvements to `Queue`.
=> Small Queue improvements

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/ParJoin.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Stream.kt
Parameterizing the concurrent ops with CoroutineContext allows for easier fine-grained control.
Running streams that consume blocking apis can simply be run now with `Stream(ioStream1, ioStream2, ioStream3).parJoin(IOPool, 3)` or `normalStream.concurrently(IOPool,  ioStream)`
=> Paramterize concurrent ops with CoroutineContext

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/concurrent/PubSub.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/concurrent/QueueTest.kt
The `update` function in `PubSub` was not correctly invoking the completion for outstanding dequeues. 
To fix this I replaced the usages of `Promise` to `UnsafePromise` so we can complete the promises in a non-suspending manner. This allows for both `modify` and `update` which can modify the state with `suspend`, and `non-suspend` support.
=> Outstanding dequeues not completed on tryOffer1

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/concurrent/Queue.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/concurrent/QueueTest.kt
This PR renames `Queue.circularBuffer` to `Queue.sliding` and align behavior with `Queue.sliding` as we have today in Arrow Fx. As discussed with @danimontoya based on his usages.
This also algins the behavior with `Channel.conflated` from KotlinX.
Also adds missing support for dropping Queues.
=> Queue: support same behavior as Arrow Fx's IO Queue

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Semaphore.kt
This PR fixes the second playground for [Semaphore](https://arrow-kt.io/docs/next/apidocs/arrow-fx-coroutines/arrow.fx.coroutines/-semaphore/)
This happened because Ank currently doesn't work properly for `playground` which need to be self contained, and cannot rely on any previous imports or previosly defined code in snippets in the same file.
=> Add missing import Semaphore playground

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/ParJoin.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Pull.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/ResourceOps.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Stream.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/TerminalOps.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/callbacks.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/CancelBoundary.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/BracketTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/CallbackTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/CancellationTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/ConcurrentlyTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/InterruptionTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/ParJoinTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/PullTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/ScopeTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/StreamTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/concurrent/QueueTest.kt
Removes `TerminalOps` in favor of more precises signatures.
Closes #245.
=> Remove TerminalOps from Stream

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Schedule.kt, arrow-fx/src/main/kotlin/arrow/fx/Schedule.kt
As controversial as the event leading to this may have been it is still undeniably correct that we should properly provide credit here.
=> Credit source in schedule docs

arrow-benchmarks-fx/build.gradle, arrow-fx-coroutines/build.gradle, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Chunk.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ConcurrentVarTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/EvalOnTests.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/ParJoinTest.kt, arrow-fx-kotlinx-coroutines/build.gradle, arrow-fx-reactor/build.gradle, arrow-fx-rx2/build.gradle, arrow-fx/build.gradle, build.gradle
* Standard library is added automatically with the plugin now
* Remove old Kotest dependency
* Remove unnecessary configuration
* Fix: Protected function call from public-API inline function is prohibited
* Disable failing tests. I've created an issue with pending tests: https://github.com/arrow-kt/arrow-fx/issues/276
=> Upgrade to Kotlin 1.4.0

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Duration.kt, arrow-fx/src/main/kotlin/arrow/fx/extensions/duration.kt, arrow-fx/src/test/kotlin/arrow/fx/data/DurationTest.kt
After #262, fx had some functionality that fx-coroutines was missing. This adds duration comparison to fx-coroutines.
It also adds some instances so we get good coverage with laws.
At some point (probably best when kotlin time is stable) we should move Duration to core or something similar and add/test instances there to avoid duplicate code. Duration may also be useful outside of fx as well.
=> Add some instances to Duration and add compareTo to fx-coroutines 

arrow-fx-coroutines-kotlinx-coroutines/gradle.properties
It fixes the package name when following these changes:
* https://github.com/arrow-kt/arrow-fx/pull/257/commits/5ee1c406ce5b0c85856000d1b118cd333659bd14
* https://github.com/arrow-kt/arrow/commit/a7ce2a2c56f81f8cb2645f5b8f91b18eb8751f8f
I realized about it after checking the deployment.
=> Fix package name

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/TerminalOps.kt
In the terminal operation `firstOrError` we return `O?`. However, there is possible way to return null as we throw an instance of `NoSuchElementException`.
=> Result doesn't need to be nullable

arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/ConcurrentlyTest.kt
We test that if the `concurrently` launched fiber fails, it also fails the parent `Stream`.
When the parent `Stream` finishes it also cancels the `concurrently` launched `Stream`.
In the case that the parent `Stream` is empty, it's possible that the fiber gets canceled before it got a chance to be scheduled. This makes the test fail since it results in `Unit` instead of a failure.
=> Fix flaky test with empty stream

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt
Fixes:
> e: /arrow-fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt: (196, 3): Type mismatch: inferred type is Either<E, List<Unit>> but Either<E, List<B>> was expected
e: /arrow-fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt: (197, 5): Type mismatch: inferred type is List<Unit> but List<B> was expected
e: /arrow-fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt: (198, 26): Unresolved reference: !
=> Fix computation block in parTraverse

PULL_REQUEST_TEMPLATE, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ParTraverseTest.kt
[324](https://github.com/arrow-kt/arrow-fx/issues/324)
**READY**
The current apis parTraverseN and parSequenceN use semaphore limit as `Long` type, and convert to `Int` which can lead to overflow issue. 
This pr deprecates these methods, sets a validation check to fail the api if limit is more than `Int` range, and introduces new apis that takes limit as `Int` type.
Would like help on if I need to do something about deploying @nomisRev 
* None
=> Deprecate parTraverseN/parSequenceN with semaphore limit as Long

arrow-fx-coroutines-stream/src/main/kotlin/arrow/fx/coroutines/stream/Scope.kt, arrow-fx-coroutines-test/src/main/kotlin/arrow/fx/coroutines/predef-test.kt, arrow-fx-coroutines-test/src/test/kotlin/arrow/fx/coroutines/PredefTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/CancellableF.kt
By replacing `suspend fun catch` with `inline fun catch` in https://github.com/arrow-kt/arrow-core/pull/272, you cannot pass `suspend` lambdas anymore.
=> Deprecate @higherkind & @extension for Either

arrow-fx-coroutines-test/src/main/kotlin/arrow/fx/coroutines/predef-test.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverseEither.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverseValidated.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ParTraverseEitherTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ParTraverseValidatedTest.kt
**READY**
Completes the `parTraverse` operations for `Either` and `Validated`.
=> Complete parTraverse ops for Either and Validated

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Duration.kt
Initial deprecation cycle in favor of kotlin.time.Duration
links to: 
#18 
**READY**
This PR goes along with the changes introduced in #360 , #359
=> Deprecate arrow.fx.coroutines.Duration

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTupledN.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/parTupledN/ParTupled4Test.kt
Fixes https://github.com/arrow-kt/arrow-fx/issues/347 (I hope, assuming the word `Par` is missing in the title cc @nomisRev )
**READY**
ParTupledN arity 4 based on the arity 3 impl
I took the liberty to create a `parTupledN` package in the tests (following the approach of `parMapN`) and created a separate spec just for Arity4
Also I am using `Tuple4` from arrow core since Kotlin doesn't have an equivalent AFIK
* None
=> Implement ParTupledN arity 4

arrow-fx-coroutines-stream/build.gradle, arrow-fx-coroutines-test/build.gradle, arrow-fx-coroutines/build.gradle, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/CircuitBreaker.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Schedule.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/flow.kt, arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Stream.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/CancelBoundary.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/CancellableF.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/CircuitBreakerTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ConcurrentVarTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/EnvironmentTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/FlowTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ParTraverseTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ScheduleTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/SemaphoreTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/BracketTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/CallbackTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/ConcurrentlyTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/InterruptionTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/ParJoinTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/StreamTest.kt, arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/concurrent/QueueTest.kt, arrow-fx-kotlinx-coroutines/build.gradle, arrow-fx-stm/build.gradle, arrow-fx-stm/src/test/kotlin/arrow/fx/stm/STMTest.kt, arrow-fx-stm/src/test/kotlin/arrow/fx/stm/TVarTest.kt, build.gradle
READY ~ON HOLD (blocked by #389)~
This PR removes all breaking changes from CircuitBreaker and adds deprecation from `arrow.fx.coroutines.Duration` to `kotlin. Double` and `kotlin.time.Duration`.
It also adds `@ExperimentalTime` on all APIs using `kotlin.time.Duration`.
It removes the gradle configuration to allow `kotlin.time.Duration` so that we get proper messages.
* #389
=> Fix breaking changes CircuitBreaker, and deprecate arrow.fx.coroutines.Duration
