arrow-fx-test/src/main/kotlin/arrow/test/generators/GenK.kt

Closes: https://github.com/arrow-kt/arrow-incubator/issues/43

Fix EitherT generator to compile with latest changes

---

arrow-fx/src/test/kotlin/arrow/fx/MVarTest.kt

Temporarily diable mvar test

---

arrow-fx-test/build.gradle

Fixes #93 that came out of #90

Remove unneeded KotlinX Coroutines within arrow fx test

---

arrow-fx/src/main/kotlin/arrow/fx/IO.kt
arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt

Adds extra support for Either in IO as mentioned in #145

Add IO APIs to work with Either

---

arrow-fx-kotlinx-coroutines/src/test/kotlin/arrow/integrations/kotlinx/CoroutinesIntegrationTest.kt
arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/FluxK.kt
arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/MonoK.kt
arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/FlowableK.kt
arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/MaybeK.kt
arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/ObservableK.kt
arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/SingleK.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/AsyncLaws.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/BracketLaws.kt
arrow-fx/src/main/kotlin/arrow/fx/IODispatchers.kt
arrow-fx/src/main/kotlin/arrow/fx/IOParMap.kt
arrow-fx/src/main/kotlin/arrow/fx/IORace.kt
arrow-fx/src/main/kotlin/arrow/fx/Ref.kt
arrow-fx/src/main/kotlin/arrow/fx/internal/ConcurrentQueue.kt
arrow-fx/src/main/kotlin/arrow/fx/internal/Utils.kt
arrow-fx/src/main/kotlin/arrow/fx/internal/atomic.kt
arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Concurrent.kt
arrow-fx/src/test/kotlin/arrow/fx/EffectsSuspendDSLTests.kt

Based on https://github.com/arrow-kt/arrow-core/issues/119

Move internal atomic impl from Core

---

arrow-docs/docs/fx/polymorphism/README.md

Fixes https://github.com/arrow-kt/arrow-core/issues/135

Fix Either.fx suspend usage

---

.github/workflows/build_arrow-fx.yml
arrow-benchmarks-fx/build.gradle

PR on `ab/lifecycle-integration`

Tuning configuration

---

arrow-fx-android/build.gradle
gradle.properties

Related to https://github.com/arrow-kt/arrow/pull/2177

Configuration: Extract Android details

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Stream.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/StreamTest.kt

Rename filterNull to filterNotNull such as Kotlin Std Collections

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/concurrent/PubSub.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/concurrent/Queue.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/stream/concurrent/QueueTest.kt

Some improvements based on the work today with @danimontoya on grpc Kotlin.

Add some docs for Queue and tests

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/Compiler.kt

This PR relates to the change to inline the `Either.catch` which is in this PR: https://github.com/arrow-kt/arrow-core/pull/237.
Somehow, the compiler is not happy with the current usage at line 238 in combination with the inlined version of `Either.catch`. This PR addresses that issue by incorporating the `Either.catch` functionality in the internal `go` function.

Address `Either.catch` inline incompatibility.

---

arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ArrowFxSpec.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ConcurrentVarTest.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/EvalOnTests.kt

Fixes compilation errors from #276, I propose to tackle the `Test failure` in a seperate branch.

Fix compilation errors in tests for Kotlin 1.4.0

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Atomic.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Bracket.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/CircuitBreaker.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ConcurrentVar.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Enviroment.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Fiber.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/IQueue.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParMapN.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTupledN.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Promise.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Race2.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Race3.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/RacePair.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/RaceTriple.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Resource.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Schedule.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Semaphore.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/builders.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/cancelBoundary.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/dispatchers.kt

This PR reviews the API reference documentation for the Arrow FX Coroutines module, mainly to fix typos, rephrase some sentences, correct some old names, etc.

Review API documentation in FX Coroutines

---

arrow-fx-kotlinx-coroutines/src/test/kotlin/arrow/integrations/kotlinx/CoroutinesIntegrationTest.kt
arrow-fx-reactor/src/test/kotlin/arrow/fx/FluxKTest.kt
arrow-fx-reactor/src/test/kotlin/arrow/fx/MonoKTest.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/SingleKTests.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/AsyncLaws.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/ConcurrentLaws.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/TimerLaws.kt
arrow-fx/src/main/kotlin/arrow/fx/Promise.kt
arrow-fx/src/main/kotlin/arrow/fx/Schedule.kt
arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Async.kt
arrow-fx/src/test/kotlin/arrow/fx/EffectsSuspendDSLTests.kt
arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
arrow-fx/src/test/kotlin/arrow/fx/MVarTest.kt
arrow-fx/src/test/kotlin/arrow/fx/QueueTest.kt
arrow-fx/src/test/kotlin/arrow/fx/RefTest.kt

inline deprecated BindSyntax members

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParMapN.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/parMapN/ParMap4Test.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/parMapN/ParMap5Test.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/parMapN/ParMap6Test.kt

I had a use case for using parMapN 4. I've added support for arity 4, 5, 6.

Add arity 4,5,6 to parMapN

---

arrow-fx-coroutines-test/src/main/kotlin/arrow/fx/coroutines/ArrowFxSpec.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParMapN.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/parMapN/ParMap7Test.kt

Fixes https://github.com/arrow-kt/arrow-fx/issues/343
**READY**
`parMapN` arity 7 based on the implementation arity 6
* None

parMapN arity 7

---

arrow-fx-coroutines-test/src/main/kotlin/arrow/fx/coroutines/predef-test.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverse.kt
arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Resource.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ResourceTest.kt

resolves #341 
and adds 
- traverseResource
- traverseFilterResource
- sequence
- flatTraverseResource
- flatTraverseFilterResource
- flatSequence
- `Resource.Companion.fromClosable`, where `A : java.io.Closable`
**READY**

Improve Resource API

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTupledN.kt
arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/parTupledN/ParTupled5Test.kt

Fixes #348
**READY**
The title says everything
* None

parTupledN arity 5

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Resource.kt

Resource mapN up to 10 API

---

build.gradle

These details are already included in the project configuration files.

Clean configuration

---

arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverseEither.kt
arrow-fx-kotlinx-coroutines/src/test/kotlin/arrow/integrations/kotlinx/CoroutinesIntegrationTest.kt
arrow-fx-reactor/src/test/kotlin/arrow/fx/FluxKTest.kt
arrow-fx-reactor/src/test/kotlin/arrow/fx/MonoKTest.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt
arrow-fx-rx2/src/test/kotlin/arrow/fx/SingleKTests.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/AsyncLaws.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/ConcurrentLaws.kt
arrow-fx-test/src/main/kotlin/arrow/fx/test/laws/TimerLaws.kt
arrow-fx/src/main/kotlin/arrow/fx/Promise.kt
arrow-fx/src/main/kotlin/arrow/fx/Schedule.kt
arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Async.kt
arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Concurrent.kt
arrow-fx/src/test/kotlin/arrow/fx/EffectsSuspendDSLTests.kt
arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
arrow-fx/src/test/kotlin/arrow/fx/MVarTest.kt
arrow-fx/src/test/kotlin/arrow/fx/QueueTest.kt
arrow-fx/src/test/kotlin/arrow/fx/RefTest.kt

READY
Cross PR for https://github.com/arrow-kt/arrow-core/pull/342
* https://github.com/arrow-kt/arrow-core/pull/342

Replace invoke with bind
